WELD error:
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: javax.jms.JMSRuntimeException: [JMSClientExceptions:055199]An injected JMSContext cannot be used when there is neither a transaction nor a valid request scope.]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.jms.JMSRuntimeException: [JMSClientExceptions:055199]An injected JMSContext cannot be used when there is neither a transaction nor a valid request scope.
        at weblogic.jms.integration.injection.InjectableJMSContext.delegate(InjectableJMSContext.java:149)
        at weblogic.jms.integration.injection.ForwardingJMSContext.createProducer(ForwardingJMSContext.java:50)
        at com.airhacks.JobImpl.execute(JobImpl.java:35)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
Caused by: org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
        at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:689)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:90)
        at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:83)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
        at weblogic.jms.integration.injection.RequestedJMSContextManager$Proxy$_$$_WeldClientProxy.getContext(Unknown Source)
        at weblogic.jms.integration.injection.InjectableJ